#!/bin/bash
# because I'm tired of typing this over and over

bld () {
    if [ -z $1 ]
    then
        echo "where should I put the final product?"
        echo "./build <executable path>"
        exit
    fi

    TO_COMP=`find . -name '*.cpp' | xargs`
    clang++-3.8 -std=c++14 -o $1 $TO_COMP
}

fmt () {
    clang-format-3.8 $1 > /tmp/proj-fom-tmp
    mv /tmp/proj-fom-tmp $1
}

alias build="bld"
alias format="fmt"
